// BuiltInQuestions.swift
// Auto-generated question database for fast O(1) lookup
// Made by mpcode

import Foundation

/// Built-in questions dictionary for instant lookup
/// Key: normalized question text (lowercased, trimmed)
/// Value: correct answer
enum BuiltInQuestions {
    /// Total number of built-in questions
    static let count = 837

    /// Main dictionary for O(1) exact match lookup
    static let dictionary: [String: String] = [
        "which chieftain in the ceroli crisis event mounted a successful coup?": "Torgny",
        "what is the tallest peak in the world?": "Mount Everest",
        "who created the famous sculpture ‘the thinker’?": "Auguste Rodin",
        "who founded the ‘spanish armada’?": "Philip II",
        "in norse mythology, what variety of trees was the world tree?": "Ash",
        "at what vip level can you purchase a vip special chest that contains enough hannibal barca sculptures to unlock his expertise?": "VIP 14",
        "which country did zarathustra, of the tone poem ‘thus spoke zarathustra’, come from?": "Persia",
        "which two oceans does the panama canal connect?": "The Pacific and Atlantic Oceans",
        "what does the number of passport pages used depend on?": "Governor’s Individual Power",
        "what were maya pyramids made of?": "Stone",
        "which of the following awards daily activity points?": "Defeating barbarian troops on the map",
        "which unit type is strong against archers?": "Cavalry",
        "which of these items can not be purchased within the mysterious merchant’s boutique?": "Passport Page",
        "where was commander lohar born?": "In a remote barbarian tribe",
        "which ancient greek physicist famously discovered the concept of buoyancy while taking a bath?": "Archimedes",
        "what is the name of the revolution in 1688 which established the british constitutional monarchy?": "The Glorious Revolution",
        "who is considered the ‘father of the modern olympic games’?": "Pierre de Coubertin",
        "which european wrote the first travelogue detailing china’s history, culture, and art?": "Marco Polo",
        "which unit type is strong against cavalry?": "Infantry",
        "which astronomer proposed the heliocentric theory in the 16th century?": "Nicolaus Copernicus",
        "where did king louis xiv of france move the royal court to in 1682?": "The Palace of Versailles",
        "in norse mythology, who wielded the weapon gungnir?": "Odin",
        "what is commander lancelot good at?": "Leading cavalry units",
        "how many reward chests are awarded for reaching 60 daily activity points?": "3",
        "the two capitals of austria-hungary were budapest and which other city?": "Vienna",
        "what is commander baibars good at?": "Leading cavalry units",
        "which of the following buildings cannot be upgraded?": "Courier Station",
        "what was the relationship between the famed generals tolui and genghis khan?": "Father and son",
        "santa claus travels on a sleigh pulled by what animal?": "Reindeer",
        "which landmark in sydney, australia is shaped like sails?": "Sydney Opera House",
        "which of the seven wonders of the world were created to cure the new queen of babylon's homesickness?": "The Hanging Gardens",
        "where do most hurricanes start?": "On the open seas",
        "what does the \"from the ground up\" kingdom buff increase?": "Building Speed",
        "how many items of the same quality should i equip to complete \"ready for battle\"?": "6",
        "what is the nickname of eleanor of aquitaine in rok?": "The Wildflower Duchess",
        "during a solar eclipse, the celestial object that comes between the sun and the earth is:": "The Moon",
        "who killed hector and how does achilles die?": "Achilles; Arrow through his heel",
        "in rok, which of these commanders is not good at leading archer units?": "Saladin",
        "what was the regnal name of the last emperor of china's qing dynasty?": "Xuantong",
        "which city hosted the 2000 summer olympics?": "Sydney",
        "what is the most abundant element in the earth's crust?": "Oxygen",
        "where are the world's largest proven oil reserves located?": "Ghawar Field",
        "which of the following statements about zhuge liang in rok is incorrect?": "He excels at leading cavalry units",
        "which of the following inventions did not come about during the first industrial revolution?": "The telephone",
        "which of the following items can be used to upgrade a commander's skills?": "Commander Sculptures",
        "methods of mitigating desertification do not include:": "Overexploitation of groundwater",
        "where did the final battle between king arthur and mordred take place according to arthurian legend?": "Camlann",
        "which is the highest plateau in the world?": "The Tibetan Plateau",
        "who wrote \"the symposium\"?": "Plato",
        "which of these commanders' expertise skill is the enhanced version of an existing skill?": "Björn Ironside",
        "the borders of which of these countries extend across two continents?": "Egypt",
        "what is the nationality of pierre de fermat, who proposed fermat's last theorem?": "France",
        "which of the following is not part of mexico's flag?": "Camel",
        "in ancient egypt, which of the following was not a privilege of being a 'scribe'?": "Exempt from paying medical expenses if sick",
        "who defeated the sphinx according to greek legend?": "Oedipus",
        "during the trojan war, which greek warrior killed hector?": "Achilles",
        "in russian history, what nickname was the first tsar given for their tyranny?": "Ivan the Terrible",
        "which of the following is considered one of confucius' disciples?": "Yan Hui",
        "which two bodies of water does the suez canal connect?": "Mediterranean Sea, Red Sea",
        "which of the following is a military building?": "Scout Camp",
        "which of the following statements is a 6‑month‑old human baby most likely to make?": "Mama",
        "how many vip points can you buy with 200 gems?": "200",
        "which beverage was invented by american pharmacist john pemberton?": "Cola",
        "in which country was the somme, the most infamous battlefield in world war i, located?": "France",
        "in rok, there is a road paved with golden bricks that can be purchased for 100 gems. what is it called?": "King's Road",
        "when was the declaration of independence written?": "1776",
        "which of these is not considered a shakespearean tragedy?": "Twelfth Night",
        "which of the following is not a benefit of upgrading your tavern?": "Improves the variety of rewards in Golden Chests",
        "which of the following is the correct description for the stratosphere?": "It is warm above and cold below",
        "how many times is the character \"1\" used when you write from number 1 to number 99?": "20",
        "what age did ancient greece enter after the mycenaean civilization was destroyed?": "Dark Age",
        "which of the following is not one of lohar's skills?": "Utter Annihilation",
        "which country hosted the first ever winter olympics on january 25, 1924?": "France",
        "which prominent statesman served as the first shogun of the edo shogunate at the end of japan's warring states period?": "Tokugawa Ieyasu",
        "in which region was the empire of srivijaya located?": "Southeast Asia",
        "france and germany were both once part of what feudal kingdom?": "Francia",
        "which of the following does not award individual credits?": "Attacking Barbarians|Giving resources to allies",
        "in golden kingdom, how many passes do you need to clear to get a golden chest?": "4 Passes",
        "which technology comes right before swordsman?": "Iron Working",
        "what effects does the \"beggar\" kingdom title apply?": "Production -10%",
        "which god is taranis in celtic mythology?": "Thunder God",
        "in her in-game dialogue, who does cleopatra vii mention was assassinated by his own senators?": "Julius Caesar",
        "which of the following technologies precedes \"horsemanship\"?": "Military Discipline",
        "which war was fought between the british houses of lancaster and york for the throne of england?": "The Wars of the Roses",
        "with whom did minamoto no yoshitsune raise an army to fight taira no kiyomori?": "Minamoto no Yoritomo",
        "which of the following is not one of mulan's skills?": "Indomitable Army",
        "on average, which of the following animals is the largest?": "Blue whale",
        "what two major works are attributed to homer?": "The Odyssey and The Iliad",
        "which of the following is not one of keira's skills?": "Unruly Blood",
        "what is the largest known planet in our solar system?": "Jupiter",
        "which civilian airport is the highest above sea level?": "Daocheng Yading Airport",
        "what is commander sun tzu good at?": "Leading city garrisons",
        "who is the king of the kingdom?": "Leader of the Alliance that conquers the Lost Temple",
        "first created in ancient greece, to which profession does the hippocratic oath apply?": "Doctors",
        "how many daily activity points do you need in \"lucerne scrolls\" to claim the daily gift clue reward?": "50",
        "which art group is known as a \"national treasure\" of canada?": "Cirque du Soleil",
        "why was scurvy once a common problem for sailors?": "A lack of fresh fruit and vegetables on long voyages",
        "what is the only known short-period comet that is regularly visible to the naked eye from earth?": "Halley's Comet",
        "which of the following did not occur during the greco-persian wars?": "The Battle of Agincourt",
        "what's the primary cause of the formation of the himalayas?": "Collision between plates",
        "egyptians made paper from which material?": "Papyrus",
        "which of the following is not one of el cid's skills?": "Chivalry",
        "what is the name for the phenomenon by which organisms that are better adapted to the environment survive to pass traits to their offspring?": "Natural selection",
        "which chinese dynasty did jiang ziya help to establish?": "The Zhou Dynasty",
        "where did reggae music originate?": "Jamaica",
        "the concept of 'separation of powers' comes from which work by montesquieu?": "The Spirit of the Laws",
        "which of the following is not a component ingredient used to forge the epic weapon \"golden age\"?": "Animal Bone",
        "in rok, which commander has the nickname \"žižka of the chalice\"?": "Jan Žižka",
        "who proposed the philosophical idea of \"i think, therefore i am\"?": "Descartes",
        "which of the following fish lures its prey through bioluminescence?": "Anglerfish",
        "in the desire of victory event, how can players gain rewards?": "Training troops",
        "when upgrading your storehouse from lvl 24 to lvl 25, which resource gains the most resource-protection capacity?": "Gold",
        "how much does the 12-hour enhanced attack item increase your troops' attack by?": "5%",
        "which ceroli chieftain has the \"thawing point\" key skill?": "Frida",
        "where in italy is vatican city located?": "Rome",
        "a human fingernail is made of which material?": "Alpha-keratin",
        "which civilization was the first to have public toilets?": "Ancient Rome",
        "which of these avatar frames can be obtained from the ceroli crisis event?": "Undersea Kingdom",
        "from the 8th to the 11th century ce, what did europeans frequently call the scandinavian invaders who often ravaged their lands?": "Vikings",
        "in rok, which of the following decorations has to be purchased with gems?": "Vase",
        "what did spartacus do as a slave before leading the biggest slave rebellion of ancient rome?": "A gladiator",
        "who commanded the new model army founded by parliament during the english civil war?": "Cromwell",
        "what is the 2nd-largest constituent nation of the united kingdom?": "Scotland",
        "what is the nickname of jan žižka in rok?": "Žižka of the Chalice",
        "which of the following commanders was effectively the ruler of their kingdom, but never officially the head of state?": "Charles Martel",
        "which of the following is not a prerequisite for the military technology cartography?": "Ballistics",
        "which of these is yi seong-gye an expert in?": "Garrisoning",
        "in which year did richard the lionheart and saladin sign a truce?": "1192",
        "what is the icon for the food resource in rok?": "Corn",
        "what is the largest living species of bird in the world?": "Ostrich",
        "which ceroli chieftain has the \"sundown smash\" key skill?": "Ak & Hok",
        "which of the following events occurred after the 19th century?": "The release of Rise of Kingdoms",
        "what does the \"healing first\" kingdom buff increase?": "Healing Speed",
        "which honorary rank was the founder of kentucky fried chicken (kfc) given?": "Colonel",
        "which of the following commanders' sculptures cannot be donated to the \"past glory\" event after the lost kingdom has been opened?": "Æthelflæd",
        "which military commander was known as \"teutoburg's liberator\"?": "Hermann",
        "who owned everything in ancient egyptian kingdoms?": "The Pharaoh",
        "which of these civilizations can increase their healing speed?": "France",
        "darwin's last book primarily discussed which species' influence on soil?": "Earthworms",
        "in the \"gather resources\" stage of the mightiest governor event, how many points do you get for gathering 1 gem?": "150",
        "japanese ivy grows upward on walls and trees in order to capture energy from which source?": "Sunlight",
        "what is the largest animal on the planet?": "Blue whale",
        "which commander's active skill can inflict silence?": "Hermann",
        "which of these effects is not caused by æthelflæd's skills?": "Healing slightly wounded units",
        "which of these commanders gets the ability to convert some slain units into severely wounded units when attacking a city?": "Charlemagne",
        "which ancient chinese dynasty followed the shang dynasty?": "The Zhou Dynasty",
        "which of these holy sites grants a march speed bonus?": "Sanctum of Wind",
        "in dc comics, what is batman's real name?": "Bruce Wayne",
        "which of the following commanders in rok was the only ruler in history to defeat cyrus the great in a major battle?": "Tomyris",
        "which of the following is an economic building?": "Alliance Center",
        "which of these is used to rally alliance troops?": "Castle",
        "which of these is one of minamoto no yoshitsune's \"active skills\"?": "Kyohachiryu",
        "in rok, which commander is nicknamed \"father of conquest\"?": "Baibars",
        "what information does the item deceptive troops falsify for enemy scouts?": "Your City's unit count",
        "what resource is required to travel in the state forum?": "Action Points",
        "which unit gains a strong benefit from sun tzu's \"master strategist\" skill?": "Infantry",
        "what were the men and women hiding from on the outskirts of florence in the novella collection \"the decameron\"?": "The Black Plague",
        "the golden bear award is given out at which film festival?": "Berlin Film Festival",
        "where do adaptations come from?": "Both mutations and genetic recombination",
        "what is 3x5?": "15",
        "which of the following describes a monotheist?": "Someone who worships 1 god",
        "what is the optimal temperature for roasting a chicken on the sizzling barrel of an ottoman cannon?": "200°C",
        "how many days are in a leap year?": "366 days",
        "big ben is located in which country?": "United Kingdom",
        "in rok, which of the following is considered a boost item?": "Peace Shield",
        "which of the following was written by mary shelley?": "Frankenstein",
        "if a man with type ab blood and a woman with type b blood have a baby, which of the following statements would be incorrect?": "It could have type O blood",
        "what is the half-life of iodine-129, a radioactive isotope produced by nuclear reactors?": "15.7 million years",
        "who painted 'girl with a pearl earring'?": "Johannes Vermeer",
        "which of the following buffs can take effect during sunset canyon battles?": "Buffs from equipment",
        "which of the following materials is not typically found in jeans?": "Lead",
        "which planet in our solar system rotates the fastest?": "Jupiter",
        "when did richard the lionheart and saladin sign a truce?": "1192",
        "which of the following titles can only be used by an islamic ruler?": "Sultan",
        "which of the following illnesses can be caused by a lack of vitamin d?": "Rickets",
        "in rok, which commander has the skill \"beauty and wisdom\"?": "Cleopatra VII",
        "what race of creatures, mythical or otherwise, lived on asgard according to norse myth?": "Aesir",
        "what date is world environment day held each year?": "June 5th",
        "in the commander view page, what buff do commanders acting as a \"iron guard\" get?": "Troop Health +1%",
        "which of these items can not be obtained by defeating barbarians?": "VIP Points",
        "in sunset canyon, how many troops can you deploy at a time?": "5",
        "which of the following is not a mammal?": "Turtle",
        "why do frogs and other organisms produce so many eggs/offspring?": "The more offspring produced the more likely they will survive",
        "pandas have 5 clawed toes on as well as a sixth digit. what do pandas use their sixth digit for?": "To hold bamboo while eating",
        "in ark of osiris, how many teleports does the first alliance to occupy an obelisk earn?": "8",
        "what is commander yi seong-gye good at?": "Garrisoning",
        "which frankish ruler never held the title of king?": "Charles Martel",
        "in what era of chinese history did the \"battle of fei river\" take place where a small number of soldiers conquered a vastly superior force?": "The Eastern Jin Dynasty",
        "which continent has the lowest average temperatures?": "Antarctica",
        "which of the following is not a type of dance?": "Sumo",
        "who conquered the \"kingdom of the vandals and alans\" in the vandalic war?": "Belisarius",
        "what discovery made the deciphering of hieroglyphics possible?": "The Rosetta Stone",
        "cactus spines are actually a modified form of which other part of the plant?": "Leaves",
        "which country was england fighting against in the battle of agincourt?": "France",
        "which of these circumstances would prevent you from changing civilization?": "Ongoing troop training in your city",
        "in rok, which of sun tzu's skills is enhanced by his expertise skill?": "Art of War",
        "in rok, the throwing axeman is which civilization's special unit?": "France",
        "the greek alphabet originated from which other writing system?": "Phoenician",
        "in ark of osiris, where are you supposed to take the ark?": "A non-enemy building",
        "what effects does the \"sluggard\" kingdom title apply?": "March Speed -5%",
        "halley's comet can be observed from earth every...": "75-76 years",
        "the \"battle of las navas de tolosa\" was a major turning point in which conflict?": "The Reconquista",
        "the famous renaissance sculpture pietà was the work of which artist?": "Michelangelo",
        "the punic wars were fought by ancient rome and what other ancient empire?": "Ancient Carthage",
        "what is the nickname of k'inich janaab' pakal in rok?": "Sun of Eternal Glory",
        "who designed the djoser, the first ancient pyramid featuring a stepped design?": "Imhotep",
        "who wrote the well-known book \"sapiens: a brief history of humankind\"?": "Yuval Noah Harari",
        "which of the following is a phase of the mightiest governor event?": "Enemy Elimination",
        "in what year did einstein publish his four annus mirabilis (\"miracle papers\")?": "1905",
        "in the book of exodus, who leads the jewish people to the promised land?": "Moses",
        "which of the following musical instruments has six strings?": "Guitar",
        "which of these is not a typical stage of sewage treatment?": "Discharge",
        "combat tactics is an important military technology—what effect does it have?": "Increases Attack of all units",
        "by what other name is october also known under japan's old calendar?": "Kannazuki",
        "which organ of the potato plant do we commonly eat?": "Stem",
        "what is the in-game nickname of cleopatra vii?": "Queen of Egypt",
        "in rok, which kingdom chronicles chapter requires all fog in your kingdom to be fully explored?": "Ultimate Clarity",
        "what did the word \"marathon\" originally refer to?": "A place name",
        "in the 16th–17th centuries, which disease did the famous bird-masked \"plague doctors\" treat?": "Bubonic plague",
        "in which year was the napoleonic code established?": "1804",
        "which club has footballer lionel messi played for the longest?": "Barcelona",
        "which of the following descriptions of microscopes is false?": "They can be used to observe stars",
        "who is the hindu god of destruction, also known as the 'cosmic dancer'?": "Shiva",
        "passport pages are used when immigrating to other kingdoms. what does the number of passport pages used depend on?": "Governor's Individual Power",
        "how many olympic gold medals did african-american athlete jesse owens win in 1936?": "4",
        "hieroglyphs were part of which country's formal writing system?": "Ancient Egypt",
        "what are the poles of a magnet?": "North and South",
        "what is the capital of germany?": "Berlin",
        "which of the following is not a part of a typical human respiratory system?": "Impact wrench",
        "which of these is a line of tomoe gozen?": "My power scares even the ghosts.",
        "ashoka the great was the king of which ancient indian kingdom?": "Maurya",
        "which of the following is not a ball game?": "Fencing",
        "what is julius caesar's nickname in rise of kingdoms?": "The Uncrowned Emperor",
        "when did the war of the austrian succession take place?": "1740-1748",
        "in which theater was beethoven's symphony no. 5 in c minor debuted in 1808?": "The Theater an der Wien",
        "which state is home to the walt disney company?": "California",
        "what is a 'light-year' a measure of?": "Distance",
        "which title did pierre de coubertin, founder of the international olympic committee, hold?": "Baron",
        "which of the following courses are you most likely to take in law school?": "Intro to Criminal Law",
        "in ark of osiris, which speedup can you use?": "Healing Speedup",
        "which of these city themes looks like a vehicle?": "On Wings of Sailcloth",
        "a decrease in which of the following metrics might indicate increasing nearness to a state of vacuum?": "Air pressure",
        "what animal is the mascot of the 2022 winter olympics based on?": "Panda",
        "what can \"masonry\" technology help you to improve?": "The building speed of buildings in your city",
        "what is the effect of the accessory \"vengeance\"?": "Counterattack Damage +8%",
        "which of the following works was written by the french playwright pierre corneille?": "Le Cid",
        "which of these equipment is of legendary quality?": "The Milky Way",
        "the alliance technology \"territory guardian\" increases which attribute of troops when battling in alliance territory?": "Attack",
        "where was the rallying point for the first crusade?": "Constantinople",
        "which of the following cities is the capital of france?": "Paris",
        "after the lost kingdom opens, what item do you have to spend to teleport to and from the lost kingdom?": "Random Teleport",
        "how many troops can governors send with a level 17 city hall or above?": "4",
        "what is the chemical symbol of antimony?": "Sb",
        "who was the first woman to win a nobel prize?": "Marie Curie",
        "the city decoration \"ishtar gate\" is a tribute to which of the following civilizations?": "Babylonia",
        "which two cities does portugal's dom luís i bridge connect?": "Porto, Vila Nova de Gaia",
        "what level does your city hall have to be to enter the iron age?": "Lvl 10",
        "which of the following constellations is shaped like a crown?": "Corona Borealis",
        "what is the name of the turkish straits that divide europe from asia?": "The Bosphorus",
        "which pharaoh ordered the construction of the abu simbel temples?": "Ramesses II",
        "in which of these works does sherlock holmes make his first appearance?": "A Study in Scarlet",
        "which of these is not one of cao cao's skills?": "Battle of Sorrow",
        "which commander is reputed to have said, \"i came, i saw, i conquered\"?": "Julius Caesar",
        "which of these actions can be performed by alliance leaders and titled officers, but not non-titled officers?": "Sign up for Ark of Osiris",
        "using a troop led by julius caesar and cleopatra vii, which of the following actions will unlock the achievement \"immortal longings\"?": "Attack a city",
        "in rok, which commander has the title \"beloved of thoth\"?": "Thutmose III",
        "which of these characters is from \"twenty thousand leagues under the seas\"?": "Captain Nemo",
        "who wrote alice's adventures in wonderland?": "Lewis Carroll",
        "who was the father of hannibal?": "Hamilcar Barca",
        "charles macintosh crafted a very early version of a raincoat from which material?": "Rubber",
        "how often is the fifa world cup held?": "Every 4 years",
        "which of the following organs is part of the human respiratory system?": "Lungs",
        "what does the \"mobilize for war\" kingdom buff increase?": "Training Speed",
        "which composer wrote the opera 'the ring of the nibelung'?": "Wagner",
        "what country was sigmund freud, the father of psychoanalysis, from?": "Austria",
        "who founded the 'malacca sultanate'?": "Parameswara",
        "which is the viking civilization's special unit?": "Berserker",
        "where was pablo picasso born?": "Iberia",
        "what country is not in europe?": "Egypt",
        "which of the babylonian codes of law was the first full set of written laws in recorded history?": "The Code of Hammurabi",
        "which modern-day city was shakespeare's globe theater built in?": "London",
        "which of these countries did not participate in the northern seven years' war (1563-1570)?": "The United Kingdom",
        "the prehistoric humans known as 'homo floresiensis' are also commonly referred to as?": "Hobbits",
        "what is the main ingredient in salt?": "Sodium chloride",
        "the daily physical activities of the maya people did not include:": "Penguin tossing",
        "after the students at the lyceum of wisdom finish their lessons, what building in your city do they return to?": "Academy",
        "the 24 'solar terms' are a traditional chinese calendar system used for what purpose?": "Agriculture",
        "when achilles refuses to fight, patroclus puts on achilles armor, fights the trojans, and dies. who is patroclus killed by?": "Hector",
        "which of the following is not a 'cold weapon'?": "Handgun",
        "who authored the tragedy 'medea'?": "Euripides",
        "shanghai's jin mao tower has how many floors?": "88",
        "which commander is commonly regarded as having exemplified the ideal of the 'bushido spirit'?": "Kusunoki Masashige",
        "which of the following is not one of julius caesar's skills?": "Military Life",
        "what was the original purpose of the great pyramid of giza?": "Pharaoh Khufu's tomb",
        "which of the following nations is the closest to the north pole?": "Finland",
        "which technology comes right before heavy cavalry?": "Scale Armor",
        "which artist painted the world-famous 'girl with a pearl earring'?": "Johannes Vermeer",
        "what do you have to do to earn the witness protection achievement?": "Change your nickname 10 times",
        "which of the following laureates won a nobel prize in two different fields?": "Marie Curie",
        "what is the shape of a soccer goal when viewed from the front?": "A rectangle",
        "which of these animated movies was not directed by hayao miyazaki?": "Paprika",
        "in 1970, an apollo mission attempted to land on the moon. due to a technical issue, it only managed to orbit around the moon and return to earth. what was the name of the mission?": "Apollo 13",
        "the gallic rooster is an official national symbol of which country?": "France",
        "why was british nurse florence nightingale known as 'the lady with the lamp'?": "She would inspect patients at night",
        "which of these alliance officers bestows a research speed boost?": "Counselor",
        "what's the name of the parrot portrait in rok?": "Fogsworth",
        "what useful tool did famed carpenter lu ban invent?": "The saw",
        "what is the largest city in the uk by area?": "London",
        "the cathedral of notre-dame de paris was built in which style?": "Gothic",
        "In Chinese mythology, what kind of creature is Jingwei?": "Bird",
        "in rok, which of the following commanders excels at leading siege units?": "Margaret I",
        "how many letters are used in today's version of english?": "26",
        "in which year was the soviet union formally established?": "1922",
        "which of the following is not a 'low country' of europe?": "The United Kingdom",
        "wales officially became part of the kingdom of great britain during the reign of which king?": "Henry VIII",
        "which planet in our solar system is closest to the sun?": "Mercury",
        "who was the director of the game that won game of the year at the game awards 2022?": "Hidetaka Miyazaki",
        "which unit type does cao cao excel in leading?": "Cavalry",
        "which ancient egyptian pharaoh's tomb did british archaeologist howard carter discover in 1922?": "Tutankhamun",
        "who was the author of the novel 'lord of rings'?": "J.R.R. Tolkien",
        "mutations are important because they bring about what?": "Genetic variation needed for a population to evolve",
        "which chieftain from the ceroli crisis event is well-versed in poison magic?": "Dekar",
        "which of the following is considered a metallic resource?": "Iron",
        "what animal is the 'tigris' named after in ancient greek?": "Tiger",
        "which of the following is not a natural resource?": "Clothing",
        "according to the tale of the she-wolf in roman mythology, what came of the twins she nurtured, romulus and remus?": "Romulus became the founder and the first king of Rome",
        "advantages of johannes gutenberg's printing press include all of the following except": "Increase in church power",
        "after a venus flytrap catches an insect, how does it digest and absorb the prey?": "The inner flaps of the leaves secrete a digestive fluid",
        "after its foundation in the 6th century bce, which institution of the roman republic served as a consultative parliament?": "The Senate",
        "a human fingernail is made of what?": "Alpha-keratin",
        "ancient egyptian history spans how many kingdoms?": "3 - Old, Middle, New",
        "apart from \"number of scouts\" and \"power\", which of the following scout camp parameters can also be upgraded?": "Scout March Speed and Exploration Range",
        "apart from \"times you can be helped\" and \"power\", which of the following alliance center parameters can also be upgraded?": "Reinforcement Troop Capacity",
        "ashoka the great was the king of which ancient kingdom?": "Maurya Dynasty",
        "at which vip level do you permanently unlock a second building queue?": "Level 6",
        "before leading the biggest slave rebellion of ancient rome, what was spartacus?": "Gladiator",
        "big ben is located in which of the following countries?": "United Kingdom",
        "broccoli is rich in which vitamin?": "Vitamin C",
        "china's crosstalk sketch comedy format originates in three places: tianqiao in beijing, the quanty bazaar in tianjin and where in nanjing?": "Fuzimiao",
        "china's temple of heaven was built during the reign of which emperor?": "The Yongle Emperor (Zhu Di)",
        "combat tactics is an important military technology – what effect does it have?": "Increase attack to all units",
        "darwin's las book primarily discussed which species' influence on soil?": "Earthworms",
        "during china's warring states period, which state defeated the other six and built the unified chinese empire?": "Qin",
        "during the renaissance, why was florence significant?": "Birthplace of the Renaissance",
        "during the second punic war, in which battle did a vastly outnumbered hannibal defeat a roman army?": "The Battle of Cannae",
        "during which emperor's reign was the roman colosseum completed?": "Titus",
        "during which season are nights relatively short and days relatively long?": "Summer",
        "edward viii became king of england in january 1936. later in the same year, in which month did he give up the throne?": "December",
        "egypt's economy was primarily based on what?": "Agriculture",
        "elbe day was the meeting of which two armies during world war ii?": "USA and USSR",
        "elder brother of zeus": "Poseidon",
        "equipment with special talent bonuses will have their attributes enhanced by what percentage when equipped to a commander with the corresponding talent?": "30%",
        "eyeglasses are composed of quartz, sand, and what?": "Petroleum",
        "first created in ancient greece, to which profession does hippocratic oath apply?": "Doctors",
        "first general of the edo shogunate?": "Tokugawa Ieyasu",
        "for which disease did edward jenner, known as the father of immunology, develop a vaccine ?": "Smallpox",
        "founder of edo bakufu?": "Tokugawa Ieyasu",
        "french national day is on july 14 in order to coincide with which historical event?": "Storming of the Bastille",
        "from the 17th to 19th centuries, the kingdom of prussia was mostly in which modern country?": "Germany",
        "from the 8th to the 11th century ce, what did europeans frequently call the scandinavian invaders who frequently ravaged their lands?": "Vikings",
        "galileo's leaning tower of pisa experiment overturned a theory of which ancient greek scientists?": "Aristotle",
        "held in 1929, how long did the first academy awards (\"oscars\") ceremony take?": "15 minutes",
        "henry i took the throne of englnd in the year 1100 after which relative died?": "His Brother",
        "homer's 'the iliad' focuses on events happening during which war or battle?": "The Trojan War",
        "how did saladin change the middle east?": "Palestine",
        "how do you get alliance technology credits?": "By donating to the Alliance",
        "how long does the \"basic army expansion\" boost last?": "4 hours",
        "how long does the item builder recruitment last?": "2 days",
        "how many action points can a governor have?": "1000",
        "how many bones does an adult human have?": "206",
        "how many elite commanders are there in the game?": "5",
        "how many fingers does the cartoon character mickey mouse have on each hand?": "4",
        "how many floors is shanghai jin mao tower?": "88",
        "how many olympic gold medals did african-american jesse owens win in 1936?": "4",
        "how many phases are there in the mightiest governor event?": "5",
        "how many pieces of normal iron ore must be combined to make a piece of advanced iron ore?": "4",
        "how many scouts can the scout camp hold at once?": "3",
        "how many separate khanates or empires had the mongol empire fractured into by the time of kublai's death in 1294?": "4",
        "how many times can you be helped if your alliance center is level 14?": "18",
        "how many times can you receive alliance help if your alliance center is level 25?": "30",
        "how many times is the character 1 used when you write from numbers 1 to number 99?": "20",
        "how much will an enhanced attack (advanced) item increase your attack?": "10%",
        "how much will an enhanced gathering item increase your gathering speed?": "50%",
        "how was the gutenberg bible put into mass production?": "Movable type printing press",
        "in 1998, the 16th fifa world cup was held in which country?": "France",
        "in ancient greece which philosopher liked to discuss ideas on a street which then got the name \"peripatetic school\"?": "Aristotle",
        "in ancient greek mythology, who was hermes' father?": "Zeus",
        "in ancient greek mythology, who was the wife of hades, the king of the underworld?": "Persephone",
        "in ark of osiris which speedup can be used?": "Healing Speed Up",
        "in china's han dynasty, who opened the silk road on the orders of emperor wu?": "Zhang Qian",
        "in greek mythlogy, which hero quested for the golden fleece?": "Jason",
        "in greek mythology, to whom did paris the prince of troy give golden apple inscribed with to the most beautiful goddess?": "Aphrodite",
        "in greek mythology, what is the goddess eos known as?": "Goddess of the Dawn",
        "in greek mythology, what is the relationship between zeus and hermes?": "Father and son",
        "in greek mythology, what was achilles' only weak point?": "His heel",
        "in greek mythology, what was the name of hades' 3-headed dog which guarded the gates of the underworld": "Cerberus",
        "in morse code, what is the length in dots between two words?": "7",
        "in most cases, what kind of mosquitoes will drink animal blood?": "Female mosquitos",
        "in most cases, which kind of lion has a mane?": "Adult male",
        "in norse mythology, who does the hammer mjolnir belong to?": "Thor",
        "in rok, the hwarang is which civilization's special unit?": "Korea",
        "in russian history, what nickname was the first tzar given for their tyranny?": "Ivan the Terrible",
        "in the commander view page , what buff do commanders acting as a \"charge captain\" get?": "+1% Rally Attack & Rally Troop March Speed",
        "in the commander view page , what buff do commanders acting as a \"iron guard\" get?": "+1% Troop Health",
        "in the commander view page , what buff do commanders acting as a \"king head\" get?": "+1% Troop Defense and Health",
        "in the commander view page , what buff do commanders acting as a \"ranger\" get?": "+5% XP Gain & Damage vs. Barbarians (none of these answers)",
        "in the commander view page , what buff do commanders acting as a \"supply captain\" get?": "+5% Gathering Speed and Troop Load",
        "in the commander view page , what buff do commanders acting as a \"tax officer\" get?": "+5% Gathering Speed",
        "in the commander view page, what buff do commanders acting as a \"drillmaster\" get?": "+1% Troop Attack",
        "in the commander view page, what buff do commanders acting as a \"bloodfist guard\" get?": "1% Troop health",
        "in rok, which building can you use to view your kingdom's history?": "Monument",
        "in the simplified maslow's hierachy of needs, which need is at the top of the pyramid?": "Self-Actualization",
        "in what country did the \"battle of marengo\" take place?": "Italy",
        "in what year did the late show with david letterman first premiere?": "1993",
        "in which city is denmark's statue of the little mermaid located?": "Copenhagen",
        "in which country did the carlist wars take place during the 19th century?": "Spain",
        "which country did zarathustra, of the tone poem \"thus spoke zarathustra\", come from?": "Persia",
        "in which country is the mysterious stonehenge located?": "United Kingdom",
        "in which country was air conditioning invented?": "USA",
        "in which country was carlsberg group, a leading brewer, founded in 1847?": "Denmark",
        "in which country was the famed revolutionary and military strategist simón bolívar born?": "Venezuela",
        "in which country was the microscope invented?": "The Netherlands",
        "in which english palace did the \"star chamber\" sit?": "Palace of Westminster",
        "in which gallery is the mona lisa currently held?": "The Louvre",
        "in which uk city were the beatles founded in 1960?": "Liverpool",
        "in which year did alexander fleming discover penicillin?": "1928",
        "in which year was the first edition of \"the diary of anne frank\" published?": "1947",
        "in which year was the first wimbledon tennis championship held?": "1877",
        "insufficient intake of which element may case thyromegaly?": "Iodine",
        "karst landform cause": "Dissolution of soluble rocks",
        "keira once defied the world's expectations about her in a glorious battle. where did this battle take place?": "Sunset Canyon",
        "lactose intolerance is caused by a shortage of what?": "Lactase",
        "legendary commander of the joseon dynasty, yi sun-sin, sacrificed his life in which famous battle?": "Battle of Noryang",
        "lost city": "The Incas",
        "machu picchu is a notable relic of which civilization?": "The Incas",
        "movable type was first used in which country?": "China",
        "mutations are a change in what?": "DNA",
        "national emblem of ireland": "Harp",
        "northern humanists like erasmus were most commonly known for what?": "Interest in religion and social form",
        "of the 12 chinese zodiac animals, which comes first?": "Rat / Mouse",
        "of the below commanders, which is best suited to lead troops against archer enemies?": "Cao Cao",
        "of the below commanders, which is best suited to lead troops against cavalry enemies?": "Sun Tzu",
        "of the below commanders, which is best suited to lead troops against infantry enemies?": "Hermann",
        "of the below commanders, which is best suited to lead troops when gathering resources?": "Seondeok",
        "of the following nations, which has the smallest area?": "Vatican City",
        "of the following, which is most likely to have directly led to the bronze age?": "Bronze is harder and more durable than other metals available at the time",
        "official measure martin luther?": "Edict of Worms",
        "old part empire now on which asian country lands": "Iran",
        "on its tragic maiden voyage, what was the titanic's intended destination?": "New York",
        "on which continent did the serval first live?": "Africa",
        "on which continent is the human race generally thought to have originated?": "Africa",
        "one \"day\" on the planet venus is approximately equal to how many earth days?": "243 days",
        "one of the knights of the round table": "Lancelot",
        "pandas have 5 clawed toes as well as a sixth digit. what do pandas use their sixth digit for?": "To hold bamboo while eating",
        "queen guinevere fell in love with which knight of the round table according to arthurian legend?": "Lancelot",
        "queen victoria of england was part of which royal house?": "The house of Hanover",
        "raphael is best known for his creation of which of the following?": "School of Athens",
        "renaissance painters in flanders, as in italy, tended to produce what type of artwork?": "Realistic",
        "since its founding in 1863, how many times has the international comittee of the red cross won the nobel peace prize?": "3",
        "the \"el nino\" phenomenon is named after which of these festivals?": "Christmas",
        "the \"independence march\" is the national anthem of which country?": "Turkey",
        "the \"american dream\" is rooted in which of these documents?": "The Declaration of Independence",
        "the \"windsor knot\" was made popular by which king of england?": "Edward VIII",
        "the 1000 point achievement chest includes:": "Epic Commander sculpture",
        "the air often feels fresher after a thunderstorm because it has been enriched with which gas?": "Ozone",
        "the alliance technology \"territory gaurdian\" increases which attribute of troops when battling in alliance territory?": "Attack",
        "the bastille, a prison once located in the center of paris, france, originally served what purpose?": "Defensive fortress",
        "the cathedral of notre-dame de paris was build on which style?": "Gothic",
        "the cone-shaped winds of tornadoes are notable for doing what?": "Spinning",
        "the differences among a species, like different bird beaks, are called?": "Variations",
        "the dragonfly cutter was the weapon of choice of which legendary warrior?": "Tadakatsu Honda",
        "the famous renaissance sculpture pieta was the work of which artist?": "Michelangelo",
        "the flag of which country holds the world record of being the oldest continuously used national flag?": "Denmark",
        "the four biggest musicals in the world are cats, les miserables, miss saigon, and?": "The Phantom of the Opera",
        "the four major varieties of guzheng in ancient china were the haozhong, luqi, jiaowei, and the...?": "Raoliang",
        "the greek alphabet originated from which other writing system": "Phoenician",
        "the great asoka, which was the king of the ancient indian kingdom": "Maurya",
        "\"the end justifies the means\" was a key belief of the author of \"the prince\". what was his name?": "Machiavelli",
        "\"tongwancheng\" was the capital of which ethnic group from ancient china?": "The Xiongnu",
        "the kingdom title 'queen' increases which of the following?": "Gathering Speed",
        "the last emperor of holy roman empire": "Francis II",
        "the luger pistol, manufactured for the german army during ww2, uses which type of ammo?": "9mm Parabellum",
        "the military leader charles martel was not known for which of the following?": "Leading cavalry units",
        "the more genetic variation a population has, the more likely it is that some individual will what?": "Survive",
        "the mughal empire carried islam to where?": "Most of India",
        "the novel romance of the three kingdoms begins near the end of which chinese dynasty": "Han",
        "the phoenician civilization originated in which part of the world?": "The Eastern Mediterranean",
        "the process of combining atoms is known as what?": "Fusion",
        "the process of splitting atoms is known as": "Fission",
        "the renaissance was a \"rebirth\" of": "Classical Culture",
        "the taj mahal was built during which indian dynasty?": "The Mughal Dynasty",
        "the three great philosophers of ancient greece were plato, aristotle, and?": "Socrates",
        "the three kingdoms of korea where baekje, silla, and?": "Goguryeo",
        "the throwing axeman is which civilization's special unit?": "France",
        "the two capitals of austria - hungary were budapest and?": "Vienna",
        "the zeppelin was invented by engineers from which country?": "Germany",
        "to which army did the \"varangian guard\" belong?": "The Byzantine army",
        "to whom did india give title mahatma?": "Mohandas Karamchand Gandhi",
        "under normal circumstances, which layer of the sun can we see with the naked eye?": "Photosphere",
        "unit type strong against infantry?": "Archer",
        "wealthy family in florence": "Medicis",
        "what animal is the \"tigris\" named after in ancient greek": "Tiger",
        "what are arrows of resistance used for?": "Upgrading Watch Tower",
        "what are the books of covenant used for?": "Upgrading Castle",
        "what are the dimensions of the fog cleared by a kingdom map item?": "10x10",
        "what are the wind-shaped cones of tornadoes famous for?": "Spinning",
        "what caused the death of the outstanding statesmen and military strategist, pericles?": "A plague",
        "what causes lunar eclipses?": "The earth moves directly between the sun and the moon",
        "what causes the distinctive smell in the air after it rains?": "The influence of actinomycetes",
        "what chieftain from the ceroli crisis event is well-versed in poison magic?": "Dekar",
        "what color is a polar bears skin?": "Black",
        "what did che guevara study in college?": "Medicine",
        "what did theodorus van gogh, the younger brother of famed dutch painter vincent van gogh, do for a living?": "Art Dealer",
        "what discovery made the deciphering of hieroglyphics possible ?": "Rosetta stone",
        "what does alliance skill \"fully loaded\" do?": "Increases alliance members' gathering speed for one type of resource",
        "what does alliance skill \"nature's gift\" do?": "Summon resources point in a selected area (cannot be used in the lost kingdom)",
        "what does the word \"formua\" in \"formula 1 racing\" refer to?": "The rules which participating cars must follow",
        "what four words saying did oda nobunaga live by?": "Rule With Absolute Force",
        "what is a light year a measure of?": "Distance",
        "what is a monotheist?": "Only believe in one god",
        "what is belisarius' nickname?": "Last of the Romans",
        "what is china's earliest known book of military strategy?": "Sun Tzu's \"The Art of War\"",
        "what is commander baybars good at?": "Leading cavalry units",
        "what is commander eulji mundeok good at?": "Leading infantry units",
        "what is commander hermann good at?": "Leading archers",
        "what is commander keira good at?": "Leading archers",
        "what is commander osman i good at?": "Attacking Cities",
        "what is julius caesar's nickname?": "Uncrowned king",
        "what is the center of a hurricane called?": "Eye",
        "what is the champion keira's nickname?": "The Red Chameleon",
        "what is the commander hannibal barca good at?": "Attacking cities",
        "what is the conversion ratio of amperes (a) to milliamperes (ma)?": "1/1000",
        "what is the deepest known trench in the world?": "The Mariana Trench",
        "what is the default rallied troop capacity when your castle is level 25?": "2 million",
        "what is the default transportation capacity if your trading post is level 25?": "5 million",
        "what is the duration of the builder recruitment item?": "2 days",
        "what is the hardest part of the human body?": "Tooth Enamel",
        "what is the highest level a city hall can reach in rise of kingdoms?": "25",
        "what is the length of a marathon in kilometers?": "42.2 Km",
        "what is the location of the mysterious stoneage?": "Germany",
        "what is the main purpose of white blood cells in the human body?": "Fighting Infection and disease",
        "what is the most abundant element on earth's crust?": "Oxygen",
        "what is the name for electricity produced by water power using large dams in a river?": "Hydroelectric energy",
        "what is the name for renewable energy derived from burning organic materials such as wood and alcohol?": "Biomass",
        "what is the name of the renewable energy derived from burning organic materials such as wood and alcohol?": "Biomass energy",
        "what is the national emblem of ireland": "Harp",
        "what is the primary cause of karst landforms?": "The dissolution of soluble rocks",
        "what is the root cause of altitude sickness ?": "Rapid exposure to low amounts of oxygen at high elevation",
        "what is the softest material known to mankind?": "Talc",
        "what is the troop health bonus you can get from a fully upgraded hospital?": "1%",
        "what is the world's oldest film festival?": "Venice Film Festival",
        "what outstanding contribution to science won biologist karl landsteiner the nobel prize?": "Discovering the human blood groups",
        "what provided the major economic support for the renaissance?": "Wealthy Patrons",
        "what two countries together made up the \"iberian union\"?": "Portugal and Spain",
        "what was another usage of gin, aside from being a popular drink, in the 18th century?": "Medicine",
        "what was the famous speech by otto von bismarck regarding in 1862?": "Blood and Iron",
        "what's does the \"skillful craftsman\" alliance skill do when used?": "Greatly increases alliance flag construction speed",
        "when a governor's city hall reaches level 25, how many farms can they build?": "4",
        "when achilles refuses to fight, patroclus puts on achilles armor, fights the trojans, and dies, who is patroclus killed by?": "Hector",
        "when catching and releasing deep sea fish,why is it important to pierce their swim bladder?": "To prevent them from dying of distended swim bladders",
        "when did dinosaurs first exist?": "Triassic",
        "when did the war of austrian succession take place?": "1740 – 1748",
        "when is the international day of forests?": "March 21",
        "when is the world no tobacco day?": "May 31",
        "when were bicycles introduced to europe?": "The 19th Century",
        "where did genghis khan start building his mongolian empire?": "Asia",
        "where did king john of england agree to the magna carta in 1215?": "Runnymede",
        "where did the renaissance begin?": "Italy",
        "where did the soldiers of ancient rome get their weapons and armor?": "Themselves",
        "where is the capital of scotland?": "Edinburgh",
        "where was the first winter olympics held in 1924?": "France",
        "where was the world heritage terracotta army found?": "In a royal mausoleum",
        "which ancient civilization built the \"lost city\" of machu picchu?": "The Incas",
        "which ancient egyptian pharaoh's tome did british archaeologist howard carter discover in 1922?": "Tutankhamun",
        "which ancient greek scholar laid the foundations for future european mathematics and authored the \"elements\" of geometry?": "Euclid",
        "which artist designed st. peter's basilica in the vatican?": "Michelangelo",
        "which artist painted girl with a pearl earring?": "Johannes Vermeer",
        "which buff can be acquired from occupying a sanctum of courage?": "Increase EXP gained by commanders",
        "which building was originally built in london to house the great exhibition of the works industry of all nations held in 1851?": "The Crystal Palace",
        "which city defeated sparta in the \"battle of leuctra\"?": "Thebes",
        "which city-state of ancient greece was known for its brutal military training and bravery?": "Sparta",
        "which civilian airport is above sea level?": "Daocheng Yading Airport",
        "which civilization gives a 5% attack bonus to cavalry units?": "Germany",
        "which civilization increases hospital capacity?": "Byzantium",
        "which civilization offers increased hospital capacity?": "Byzantine",
        "which commander excels at leading infantry?": "Richard I",
        "which commander is commonly regarded as having exemplified the ideal of \"bushido spirit\"?": "Kusunoki Masashige",
        "which commander is known as kamakura's warlord?": "Minamoto no Yoshitsune",
        "which commander is known as the conqueror of chaos?": "Cao Cao",
        "which commander is known as \"the immortal hammer\"": "Charles Martel",
        "which commander is known as the lady of the mercians?": "Æthelflæd",
        "which commander is named death hydromel?": "Sarka",
        "which commander is nicknamed carthage's guardian?": "Hannibal Barca",
        "which commander is nicknamed the father of conquest?": "Baibars",
        "which commander is nicknamed the roaring barbarian?": "Lohar",
        "which commander showed their military genius in the battle of poitiers in the 8th century ad?": "Charles Martel",
        "which commander signed a peace treaty with saladin in 1192?": "Richard I",
        "which commander was considered an enemy of rome from an early age?": "Hannibal Barca",
        "which commander was in charge of capturing constantinople at the age of 21?": "Mehmed II",
        "which commander was known as the celtic rose?": "Boudica",
        "which commander was nicknamed mead of death?": "Sarka",
        "which commander was paired with minamoto?": "Tomoe Gozen",
        "which commander was part of the battle of red cliffs?": "Cao Cao",
        "which country gave the statue of liberty ti american people as a gift?": "France",
        "which country in asia overlaps with the former parthian empire?": "Iran",
        "which country is catalhoyuk (çatalhöyük) located in?": "Turkey",
        "which country is not in europe?": "Egypt",
        "which country started the tradition of the 8-hour workday?": "United Kingdom",
        "which country was marco polo, a famous explorer and merchant, born in?": "Republic of Venice",
        "which country was the first to invent perfume?": "Cyprus",
        "which dutch scientist is know as \"the father of microbiology\"?": "Antonie van Leeuwenhoek",
        "which emperor issued the proclamation of milan?": "Constantine I",
        "which emperor was named the \"khan of heaven\" by various turkic nomads during the sui and tang dynasties?": "Emperor Taizong of Tang",
        "which ethnic group founded the earliest civilization of mesopotamia?": "The Sumerians",
        "which european country's king funded christopher columbus' famous expedition?": "Spain",
        "which european wrote the first travelogue detailing china's history, culture, and art?": "Marco Polo",
        "which famous and influential family did the famous renaissance art patron duke lorenzo belong to?": "Medici",
        "which french monarch was known as saint louis?": "Louis IX",
        "which gas makes up more than 90% of mars' atmosphere?": "Carbon Dioxide",
        "which german psychologist discovered the human brain's forgetting curve?": "Hermann Ebbinghaus",
        "which group conquered the byzantine empire?": "The Ottomans",
        "which historical figure is entombed in palenque's temple of the inscriptions?": "Pakal the Great",
        "which if the following buffs can take effect during sunset canyon battles?": "Buffs from equipment",
        "which inventor built the world's first electric locomotive in 1837?": "Robert Davidson",
        "which is not a king skill?": "Relief",
        "which is recognized by the guinness book of world records as having the largest cumulative circulation of any single-author comic?": "Eiichiro Oda / One Piece|One Piece",
        "which is the largest animal on the planet?": "Blue Whale",
        "which is the longest continental mountain range on earth?": "The Andes",
        "which is the smallest known snake species?": "Barbados threadsnake",
        "which mammalian order does suidae belong to?": "Artiodactyla",
        "which musical instrument has six strings?": "Guitar",
        "which nation was not involved in the battle of waterloo?": "Italy",
        "which of the following accurately describes the arctic circle": "Polar Day and Polar Night are phenomenons that occur there",
        "which of the following achievements must be completed before the \"special snowflake\" achievement?": "Long-range strike",
        "which of the following best describes a clownfish?": "Tropical marine fish",
        "which of the following can not be found in a silver chest at the tavern?": "Lvl. 3 Tome of knowledge",
        "which of the following can not be found in alliance shops?": "Golden Key",
        "which of the following cat breeds is known for being hairless?": "Sphynx",
        "which of the following cities was the first to have an underground rapid transit system?": "London",
        "which of the following civilizations cannot buff their cavalry?": "The Ottomans",
        "which of the following civilizations increase the damage of active commander skills by 5%?": "Ottomans",
        "which of the following commander excels at gathering resources?": "Cleopatra VII",
        "which of the following commanders excels at attacking enemy cities?": "Caesar",
        "which of the following commanders excels at leading archers?": "Yi Seong-Gye",
        "which of the following commanders excels at leading cavalry?": "Minamoto no Yoshitsune",
        "which of the following commanders excels at leading infantry?": "Richard I",
        "which of the following commanders joined a rebellion against her own husband?": "Constance",
        "which of the following commanders was part of the battle of red cliffs?": "Cao Cao",
        "which of the following commanders was part of the hundred years war?": "Joan of Arc",
        "which of the following countries is located entirely in the northern hemisphere?": "None of these answers are correct",
        "which of the following did desiderius erasmus and thomas more have in common?": "Both were considered humanists",
        "which of the following doctors was the first to describe completely, and in detail, the systemic circulation and the function of the heart?": "William Harvey",
        "which of the following does not give commanders exp?": "Attacking other players",
        "which of the following does not increase an alliance's member limit": "Appointing officers",
        "which of the following does the green olympic ring represent?": "Oceania",
        "which of the following factors allows certain mixed drinks to be layered?": "Density",
        "which of the following french kings was known as the sun king?": "Louis XIV",
        "which of the following fruits, known as \"wolf peach\", were erroneously thought to be poisonous?": "Tomatoes",
        "which of the following is a decorative building?": "Stone Drum",
        "which of the following is a fossil fuel formed from marine organisms that is often found in folded or tilted layers and used for heating and cooking?": "Natural Gas",
        "which of the following is a liquid fossil fuel formed from marine organisms that is burned to obtain energy and used to manufacture plastics?": "Oil",
        "which of the following is a name for sedimentary rock formed from decayed plant materiel in swampy areas?": "Coal",
        "which of the following is a nonrenewable energy source (such as coal, oil, or natural gas)?": "Fossil Fuel",
        "which of the following is a nonrenewable energy source?": "Water",
        "which of the following is a phase of the mightiest governor?": "Enemy Elimination",
        "which of the following is a term for a valuable material of geologic origin that can be extracted from the earth": "Natural Resources",
        "which of the following is an accurate description of the mediterranean climate?": "Hot, dry summers and cool, wet winters",
        "which of the following is an alternative energy source based on splitting heavy atoms into lighter ones to release energy?": "Nuclear energy",
        "which of the following is an inexhaustible energy resource that relies on hot magma or hot dry rocks below ground?": "Geo",
        "which of the following is another name for the \"black death\" that raged across the europe during the late middle ages?": "Yersinia pestis",
        "which of the following is considered an energy source?": "Petroleum",
        "which of the following is most likely to have directly led to the bronze age?": "Bronze is harder and more durable than other metals available at the time",
        "which of the following is not a characteristic of renaissance art?": "Two-dimensional",
        "which of the following is not a reason why the renaissance began in italy?": "The black plague did not hit Italy as a result of the alps",
        "which of the following is not a suit in poker?": "Winds",
        "which of the following is not an objective of greek mythology?": "Provide a path for salvation",
        "which of the following is not king skill?": "Relief",
        "which of the following is not one of belisarius' skills?": "Thunderous Force",
        "which of the following is not one of julius caesar skills?": "Military Life",
        "which of the following is not one of matilda of flanders' skills?": "Celtic Blood",
        "which of the following is not one of osman i's skills?": "Oblique Tactics",
        "which of the following is not one of pelagius passive skills?": "Charge",
        "which of the following is not one of the major greenhouse gases in earth's atmosphere?": "Nitrogen",
        "which of the following is the world's largest island?": "Greenland",
        "which of the following is the world's first national park?": "Yellowstone National Park",
        "which of the following is zeus' elder brother in greek mythology?": "Poseidon",
        "which of the following juice is contained in the classic cocktail \"bloody mary\"?": "Tomato Juice",
        "which of the following kingdom title descriptions are incorrect?": "Prime minister has increased troop attack",
        "which of the following marine species has existed the longest?": "Nautilus",
        "which of the following physicists was born on the death anniversary of galileo galilei, and died on the birth anniversary of albert einstein?": "Stephen Hawking",
        "which of the following resources cannot be found in your jeans?": "Lead",
        "which of the following serves as the national flower of the philippines?": "Sampaguita",
        "which of the following speeches was made by the prussian prime minister otto von bismarck in september of 1862?": "Blood and Iron",
        "which of the following stories is not one of grimms' fairy tale?": "The Little Mermaid",
        "which of the following structures is a military building?": "Scout Camp",
        "which of the following vitamins is most helpful for maintaining good vision?": "Vitamin A",
        "which of the following was a general during japan's genpei war?": "Tomoe Gozen",
        "which of the following was a knight of the round table?": "Lancelot",
        "which of the following was a renaissance intellectual movement in which thinkers studied classical texts and focused on human potential and achievements?": "Humanism",
        "which of the following was also known as the eastern roman empire?": "Byzantine Empire",
        "which of the following was an enemy of richard the lionheart?": "Saladin",
        "which of the following was built at the order of shah jahan in the memory of his wife mumtaz mahal?": "Taj Mhal",
        "which of the following was not a pillar of the renaissance?": "Mannerism",
        "which of the following was not invented in china?": "Seismographs",
        "which of the following was praised by his countrymen as ancient greece's best and most honest democratic representative?": "Pericles",
        "which of the following were born in the same year as singer luciano pavarotti?": "Elvis Presley",
        "which of the following works is based on the battle of roncevaux pass, fought by charlemagne and his knights?": "The Song of Roland",
        "which of the following works was written by victor hugo?": "The Hunchback of the Notre-Dame",
        "which of these active skills belongs to charles martel?": "Immortal Shield",
        "which of these are not considered a shakespearean tragedy?": "Twelfth Night",
        "which of these artists is not considered as a baroque artist?": "Vincent van Gogh",
        "which of these avatar frames can be obtained from ceroli crisis event?": "Undersea Kingdom",
        "which of these cities hosted the olympics in 1900?": "Paris",
        "which of these cities in brazil has hosted the olympic games?": "Rio de Janeiro",
        "which of these commanders gets the ability to convert some slain units into severely wound units when attacking a city?": "Charlemagne",
        "which of these commanders was able to defeat the great charles in the battle?": "Tomiris",
        "which of these countries does the prime meridian pass through?": "Mali",
        "which of these countries is not a founding member of nato (in 1949)?": "Turkey",
        "which of these fields is not included in the list of nobel prizes?": "Mathematics",
        "which of these is an incorrect description of the \"battle of poitiers\"?": "The campaign took place during World War I",
        "which of these is an incorrect description of the \"mare imbrium\" on the moon?": "It contains a certain amount of sedimentary water.",
        "which of these is not a natural resource?": "Clothing",
        "which of these is not considered one of the five good emperors of the nerva-antonine dynasty of ancient rome?": "Commodus",
        "which of these is yi seong-gye expert in?": "Garrison",
        "which of these items can not be obtained by defeating barbarians": "VIP Points",
        "which of these items can not be purchased within the mysterious merchant's boutique?": "Passport Page",
        "which of these navigators was the first european to arrive in brazil?": "Pedro Alvares Cabral",
        "which of these nobel prizes was awarded to marie curie in 1903?": "The Nobel Prize in Physics",
        "which of these novels was not written by margaret artwood?": "Flowers for Algernon",
        "which of these two were created by leonardo da vinci?": "The Last Supper, Mona Lisa",
        "which of these was the only commander to defeat cyrus the great in battle?": "Tomyris",
        "which of these works of japanese monogatari literature describes the legend of \"kaguya-hime\"?": "The Tale of The Bamboo Cutter",
        "which official measure made it a crime to give martin luther food or shelter?": "Edict of Worms",
        "which one of the following is not one of hermann's skills?": "Irresistible",
        "which one of these animals does not lay eggs?": "Bat",
        "which part of the brain will alcohol affect?": "The Cerebellum",
        "which part of the human body contains mostly water?": "Eyeballs",
        "which period of european history, lasting from 1300 to 1600, saw renewed interest in classical culture and led to far-reaching changes in art, learning, and views of the world?": "Renaissance",
        "which philosopher wrote \"utopia\"?": "Plato",
        "which portuguese explorer sailed from the cape of good hope to india?": "Vasco de Gama",
        "which portuguese explorer was the first european to sail to the southern tip of africa?": "Bartolomeu Dias",
        "which prominent statesman served as the first general of the edo shogunate at the end of japan's warring states period?": "Tokugawa Ieyasu",
        "which roman emperor was named augustus after ending a civil war?": "Gaius Octavius",
        "which school of painting would georges seurat be a representative of?": "Pointillism",
        "which school of thought was founded by the chinese philosopher lao tzu?": "Taoism",
        "which script was the code of hammurabi engraved onto stone in?": "Cuneiform",
        "which technology comes before pavise?": "Bodkin Arrows",
        "which technology comes before swordsman?": "Iron Working",
        "which title did pierre de coubertin, founder of the international olympic committee, hold ?": "Baron",
        "which two cities does portugal's dom luis bridge connect?": "Porta, Vila Nova de Gaia",
        "which type of holy sites grant troop attack bonuses?": "Flame Altar",
        "which type of natural disaster is measured using the richter scale?": "Earthquake",
        "which unit type is strong against infantry?": "Archer",
        "which war ended the rule of the house of plantagenet and began the rule of the tudors in england?": "The Wars of the Roses",
        "which war was fought between the bristish houses of lancaster and york for the throne of england?": "The Wars of the Roses",
        "which war was fought between the british?": "War of Roses",
        "which was a lighthouse built after macedonia conquered egypt and waste of the seven wonders of the ancient world?": "The Lighthouse of Alexandria",
        "which was the only ancient civilization to develop in a tropical jungle rather than a river basin?": "The Incas",
        "while gutenberg introduced the printing press in europe, his invention was influenced by which country, the first to develop a moveable type?": "China",
        "who authored the novel \"no longer human\"?": "Osamu Dazai",
        "who came up with the trojan horse idea? who won the trojan war?": "Odysseus; The Greeks",
        "who created the famous sculpture \"the thinker\"?": "Auguste Rodin",
        "who defeated sphinx according to greek legend?": "Oedipus",
        "who designed the \"ottoman cannon\"?": "Urban",
        "who first implemented the julian calendar in rome?": "Julius Caesar",
        "who founded the \"malaca sultanate\"?": "Parameswara",
        "who founded the \"spanish armada\"?": "Philip II",
        "who founded the first persian empire?": "Cyrus the Great",
        "who founded the joseon dynasty?": "Yi Seong-Gye",
        "who founded the kamakura shogunate?": "Minamoto no Yoritomo",
        "who founded the kingdom of asturias?": "Pelagius",
        "who funded christopher colombus's travels?": "Spain",
        "who gave the famous \"i have a dream\" speech?": "Martin Luther King Jr.",
        "who initiated the first salt march?": "Mahatma Gandhi",
        "who invented the printing press?": "Johann Gutenberg",
        "who is considered the \"father of modern olympic games\"?": "Pierre de Coubertin",
        "who is cupid's mother in roman mythology?": "Venus",
        "who is responsible for ushering valiant warriors into valhalla upon death in norse mythology?": "Valkyrie",
        "who is the 'god of love' in norse mythology?": "Freyja",
        "who is the \"god of death\" in ancient greek mythology?": "Thanatos",
        "who is the commander considered an enemy of rome since childhood?": "Hannibal Barca",
        "who is the first italian to receive the \"pritzker architecture prize\"?": "Aldo Rossi",
        "who killed hector and how achilles die?": "Achilles; Arrow though his heel",
        "who made the idea \"troy\"?": "Odysseus",
        "who painted the last supper?": "Leonardo Da Vinci",
        "who painted the mona lisa?": "Leonardo da Vinci",
        "who was believed to be the prototype of king of hearts in poker?": "Charlemagne",
        "who was called \"napoleon of crime\" in some of the sherlock holmes stories?": "Professor Moriarty",
        "who was plato's teacher?": "Socrates",
        "who was praised by his countryman as ancient greece's best and most honest democratic representatives?": "Pericles",
        "who was the emperor of the first french empire?": "Napoleon Bonaparte",
        "who was the first astronaut to enter outer space?": "Yuri Gagarin",
        "who was the first consul of the roman republic?": "Lucius Junius Brutus",
        "who was the first emperor of rome?": "Gaius Octavius Augustus",
        "who was the first human woman created by hephaestus in greek mythology?": "Pandora",
        "who was the first king of italy after its unification in 1861?": "Victor Emmanuel II",
        "who was the first of henry viii's children to rule england?": "Edward VI",
        "who was the founder of the edo bakufu of japan?": "Tokugawa Ieyasu",
        "who was the founder of the mongolian empire?": "Genghis Khan",
        "who was the last emperor of all russia?": "Nicholas II",
        "who was the last emperor of the holy roman empire?": "Francis II",
        "who was the last female pharaoh of the ptolemy dynasty?": "Cleopatra VII",
        "who was the only king of england to be executed?": "Charles I",
        "who was the only us president that served more than 2 terms?": "Franklin D. Roosevelt",
        "who were the first mountaineer(s) on record to reach the summit of mt. everest?": "Tenzing Norgay and Edmund Hilary",
        "who won the trojan war?": "The Greeks",
        "who wrote alice in wonderland?": "Lewis Carroll",
        "who wrote the art of war?": "Sun Tzu",
        "who wrote the well-known book \"a brief history of time\"?": "Stephen Hawking",
        "whose autobiography \"living to tell the tale\" won them the nobel prize in literature?": "Gabriel García Márquez",
        "whose beauty is said to have been the cause of the trojan war?": "Helen",
        "whose victory was the orchestral work \"1812 overture\" composed to commemorate?": "Russian Empire",
        "why are advantageous traits more likely to be passed onto offspring?": "Because they are more likely to survive and produce",
        "why does drinking coffee make people feel more awake?": "It contains caffeine",
        "why was the dead sea given this name?": "The high-saline water prevents plants and animals from thriving near it",
        "why were the bow and stern of viking longboats designed to be symmetrical?": "To reverse direction quickly without a turn around",
        "without using buffs, how many action points can a governor have?": "1",
        "where is the mausoleum of the first qin emperor located in china?": "Shaanxi",
        "in which commander's background picture can you see a dog?": "Richard I",
        "which poet wrote \"theogony\", which describes the origins and genealogy of the greek gods?": "Hesiod",
        "which of these figures is not referenced in the title of the ancient chinese poem: \"a song of the eight immortals in drinking\"?": "Du Fu",
        "who wrote \"history of animals\"?": "Aristotle",
        "during which dynasty was china's forbidden city built?": "Ming",
        "in rok, which of the following characters does sun tzu mention in his trust dialogue?": "Mulan",
        "each animal of the chinese zodiac is associated with one of the five classical chinese elements. which element has the most zodiac animals associated with it?": "Earth",
        "what color gemstones are engraved upon the crown of the commander el cid?": "Red",
        "in greek mythology, which hero rode the flying horse pegasus?": "Bellerophon",
        "which of the below states was not part of the three kingdoms period?": "Jin",
        "\"ru ware\" is one of the most famous types of chinese pottery, known for its delicate pale blue glaze. which dynasty did it originate from?": "Song",
        "who burned down the epang palace in china built during the qin dynasty?": "Xiang Yu",
        "which of the following is not a common chinese new year tradition?": "Eating mooncakes",
        "in his in-game dialogue, which commander does sun tzu warn the governor to keep an eye on?": "Cao Cao",
        "which of these civilizations can increase their hospital capacity?": "Byzantium",
        "in ancient greece, who was the high priestess of the temple of apollo at delphi?": "The Pythia",
        "which formation is the \"imperial war drum\" armament for?": "V",
        "what was the name of the ancient greek god of wine?": "Dionysus",
        "Which two animals symbolically decorated the pschent double crown worn by the Pharaohs?": "The cobra and vulture",
    ]

    /// Get answer for exact match (O(1) lookup)
    static func getAnswer(for question: String) -> String? {
        let normalized = question.lowercased().trimmingCharacters(in: .whitespaces)
        return dictionary[normalized]
    }

    /// Check if question exists
    static func contains(_ question: String) -> Bool {
        let normalized = question.lowercased().trimmingCharacters(in: .whitespaces)
        return dictionary[normalized] != nil
    }
}
